### ISSUE TITLE
Vorname "Familienname" unrealistisch

### ISSUE THREAD

**Issue by xilefluap** [berlinonline/haeufige-vornamen-berlin#3]
In Spandau gab es nach der bereinigten Liste 2017 angeblich den Vornamen "Familienname".
Das kommt mir komisch vor. Hat sich hier ein Fehler eingeschlichen, der auch bereinigt werden sollte?

**Comment by graste** [comment]
Danke für den Hinweis. Scheint mir auch komisch. Habe mal einen PR eröffnet: https://github.com/berlinonline/haeufige-vornamen-berlin/pull/4

**Comment by knudmoeller** [comment]
Ja, das ist in der Tat nicht so, wie es sein soll! Zu den Gründen für solche Seltsamheiten siehe https://github.com/berlinonline/haeufige-vornamen-berlin#entfernung-von-einträgen-die-keine-namen-sind.

Ich habe den PR von @graste (tausend Dank!) eingepflegt und die Skripte für alle Jahre nochmal durchlaufen lassen. Änderungen gab es aber tatsächlich nur in Spandau 2017.
