### ISSUE TITLE
Unklarer Stadtteil "standesamt_i" mit jew. 1-2 Namen in 2014, 2015, 2021

### ISSUE THREAD

**Issue by DerTee** [berlinonline/haeufige-vornamen-berlin#8]
Es gibt bei den bereinigten Daten in 2014, 2015, 2021 eine einzelne Datei "standesamt_i.csv".
Das weist auf einen eigenen Stadtbezirk hin, den es so nicht in der normalen Verwaltung gibt. Ist das ein Auffangbecken für Sonderfälle die keinem Stadtteil zugeordnet werden können?

Ich fände es super wenn dazu in der Readme eine kurze Erklärung hinzugefügt werden könnte.

Hier ein Link zu einem Beispiel:
https://github.com/berlinonline/haeufige-vornamen-berlin/blob/master/data/source/2021/Vornamenstatistik%202021%20I%20in%20Berlin.csv

**Comment by knudmoeller** [comment]
Danke für den Hinweis! Ich habe ein paar kurze Infos zum Standesamt I zum README hinzugefügt: 5b5e371c46a6b8a431d01d1738ce335b84612ae2
