### ISSUE TITLE
gültige Vornamen in cleaned?

### ISSUE THREAD

**Issue by traut21** [berlinonline/haeufige-vornamen-berlin#9]
Sind A, A., B., C., H, I (m und w), K., S, X, Ý (m und w), ý gültige Vornamen im Sinne dieser Anwendung hier, als cleaned?

Was ist mit diesen Einträgen hier:
(Eigenname)     m
(Eigenname)     w
(Großvatersname)        m
(Mittelname)    w
(Vatersname)    m
"-"       m
"-"       w

ist 'evič in 2014/tempelhof-schoeneberg.csv ein gültiger Vorname? Ich kenne den nur als Endung.

**Comment by knudmoeller** [comment]
Hallo,

tatsächlich waren mir die `(*name)`-Einträge und `'evič` vor ein paar Monaten auch schon mal aufgefallen, die Arbeit daran war aber liegen geblieben. Jetzt habe ich mich, dank Ihres Hinweises, wieder daran begeben und die Arbeit endlich abgeschlossen (https://github.com/berlinonline/haeufige-vornamen-berlin/blob/master/CHANGELOG.md#120) . Vielen Dank!

Bei diesen Einträgen handelt es sich um offensichtliche Eingabefehler, daher können sie auch offensichtlich entfernt werden.

Bei den anderen (einzelne Buchstaben) bin ich mir weniger sicher. Hier ist es wahrscheinlich eher so, dass bei der Eingabe der vollständige Name nicht bekannt war (wie auch immer das passieren kann). Dazu habe ich einen Abschnitt zur [README.md](https://github.com/berlinonline/haeufige-vornamen-berlin#readme) hinzugefügt.
